"""Generator templates for strategy generation."""
from typing import Dict, List, Any
from athena.common.models import DNASpec, StrategyTemplate


TREND_FOLLOWING_TEMPLATE = """
# ---------------------------------------
# AthenaStrategy — generated by Athena AI
# Template: {template_name}
# Class:    {class_name}
# ---------------------------------------
import numpy as np
import pandas as pd
import pandas_ta as ta
from freqtrade.strategy.interface import IStrategy

class {class_name}(IStrategy):
    INTERFACE_VERSION = 3

    timeframe = '{timeframe}'
    stoploss = -0.10
    trailing_stop = True
    trailing_stop_positive = 0.02
    trailing_stop_positive_offset = 0.04

    can_short = False
    use_exit_signal = True

    startup_candle_count = {slow_period}

    # ── hyperoptable parameters ─────────────────────────────────────
    fast_period = {fast_period}
    slow_period = {slow_period}
    trend_threshold = {trend_threshold}
    rsi_period = {rsi_period}
    rsi_overbought = {rsi_overbought}
    rsi_oversold = {rsi_oversold}

    # ── position sizing ────────────────────────────────────────────
    position_size_pct = {position_size_pct}
    min_stake_usd = {min_stake_usd}
    max_stake_usd = {max_stake_usd}
    max_open_trades = {max_open_trades}
    risk_capital_pct = {risk_capital_pct}
    reserve_capital_pct = {reserve_capital_pct}

    def populate_indicators(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe['fast'] = ta.ema(dataframe['close'], length=self.fast_period)
        dataframe['slow'] = ta.ema(dataframe['close'], length=self.slow_period)
        dataframe['rsi'] = ta.rsi(dataframe['close'], length=self.rsi_period)
        dataframe['trend_strength'] = np.abs((dataframe['fast'] - dataframe['slow']) / dataframe['slow'])
        return dataframe

    def populate_entry_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe.loc[
            (dataframe['fast'] > dataframe['slow']),
            'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe.loc[dataframe['fast'] < dataframe['slow'], 'exit_long'] = 1
        return dataframe
"""

MEAN_REVERSION_TEMPLATE = """
import numpy as np
import pandas as pd
import pandas_ta as ta
from freqtrade.strategy.interface import IStrategy

class {class_name}(IStrategy):
    INTERFACE_VERSION = 3

    timeframe = '{timeframe}'
    stoploss = -0.10

    can_short = False
    use_exit_signal = True

    startup_candle_count = {mean_period}

    bb_period = {bb_period}
    bb_std = {bb_std}
    rsi_period = {rsi_period}
    rsi_overbought = {rsi_overbought}
    rsi_oversold = {rsi_oversold}
    mean_period = {mean_period}
    deviation_threshold = {deviation_threshold}

    # ── position sizing ────────────────────────────────────────────
    position_size_pct = {position_size_pct}
    min_stake_usd = {min_stake_usd}
    max_stake_usd = {max_stake_usd}
    max_open_trades = {max_open_trades}
    risk_capital_pct = {risk_capital_pct}
    reserve_capital_pct = {reserve_capital_pct}

    def populate_indicators(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe['sma'] = ta.sma(dataframe['close'], length=self.mean_period)
        dataframe['rsi'] = ta.rsi(dataframe['close'], length=self.rsi_period)
        bband = ta.bbands(dataframe['close'], length=self.bb_period, std=self.bb_std)
        dataframe = dataframe.join(bband)
        return dataframe

    def populate_entry_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dev = (dataframe['sma'] - dataframe['close']) / dataframe['sma']
        dataframe.loc[
            (dataframe['close'] < dataframe['sma']) &
            (dataframe['rsi'] < self.rsi_oversold) &
            (dev > self.deviation_threshold),
            'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe.loc[dataframe['close'] > dataframe['sma'], 'exit_long'] = 1
        return dataframe
"""

BREAKOUT_TEMPLATE = """
import numpy as np
import pandas as pd
import pandas_ta as ta
from freqtrade.strategy.interface import IStrategy

class {class_name}(IStrategy):
    INTERFACE_VERSION = 3

    timeframe = '{timeframe}'
    stoploss = -0.10

    can_short = False
    use_exit_signal = True

    startup_candle_count = {lookback}

    lookback = {lookback}
    atr_period = {atr_period}
    atr_multiplier = {atr_multiplier}

    # ── position sizing ────────────────────────────────────────────
    position_size_pct = {position_size_pct}
    min_stake_usd = {min_stake_usd}
    max_stake_usd = {max_stake_usd}
    max_open_trades = {max_open_trades}
    risk_capital_pct = {risk_capital_pct}
    reserve_capital_pct = {reserve_capital_pct}

    def populate_indicators(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe['high_max'] = dataframe['high'].rolling(window=self.lookback).max()
        dataframe['low_min'] = dataframe['low'].rolling(window=self.lookback).min()
        dataframe['atr'] = ta.atr(dataframe['high'], dataframe['low'], dataframe['close'], length=self.atr_period)
        return dataframe

    def populate_entry_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe.loc[
            (dataframe['close'] > dataframe['high_max'].shift(1)),
            'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe.loc[
            dataframe['close'] < dataframe['high_max'].shift(1) - dataframe['atr'] * self.atr_multiplier,
            'exit_long'] = 1
        return dataframe
"""

MOMENTUM_TEMPLATE = """
import numpy as np
import pandas as pd
import pandas_ta as ta
from freqtrade.strategy.interface import IStrategy

class {class_name}(IStrategy):
    INTERFACE_VERSION = 3

    timeframe = '{timeframe}'
    stoploss = -0.10

    can_short = False
    use_exit_signal = True

    startup_candle_count = {signal_period}

    momentum_period = {momentum_period}
    signal_period = {signal_period}
    momentum_threshold = {momentum_threshold}
    rsi_period = {rsi_period}

    # ── position sizing ────────────────────────────────────────────
    position_size_pct = {position_size_pct}
    min_stake_usd = {min_stake_usd}
    max_stake_usd = {max_stake_usd}
    max_open_trades = {max_open_trades}
    risk_capital_pct = {risk_capital_pct}
    reserve_capital_pct = {reserve_capital_pct}

    def populate_indicators(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe['rsi'] = ta.rsi(dataframe['close'], length=self.rsi_period)
        macd = ta.macd(dataframe['close'], fast=12, slow=26, signal=self.signal_period)
        dataframe = dataframe.join(macd)
        dataframe['momentum'] = dataframe['MACD_12_26_9'] - dataframe['MACDs_12_26_9']
        return dataframe

    def populate_entry_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe.loc[
            (dataframe['momentum'] > self.momentum_threshold) &
            (dataframe['rsi'] < 70),
            'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe.loc[
            (dataframe['momentum'] < -self.momentum_threshold * 0.5),
            'exit_long'] = 1
        return dataframe
"""

VOLATILITY_TEMPLATE = """
import numpy as np
import pandas as pd
import pandas_ta as ta
from freqtrade.strategy.interface import IStrategy

class {class_name}(IStrategy):
    INTERFACE_VERSION = 3

    timeframe = '{timeframe}'
    stoploss = -0.10

    can_short = False
    use_exit_signal = True

    startup_candle_count = {atr_period}

    atr_period = {atr_period}
    volatility_threshold = {volatility_threshold}
    tp_multiplier = {tp_multiplier}
    sl_multiplier = {sl_multiplier}

    trailing_stop = True
    trailing_stop_positive = 0.01
    trailing_stop_positive_offset = 0.02

    # ── position sizing ────────────────────────────────────────────
    position_size_pct = {position_size_pct}
    min_stake_usd = {min_stake_usd}
    max_stake_usd = {max_stake_usd}
    max_open_trades = {max_open_trades}
    risk_capital_pct = {risk_capital_pct}
    reserve_capital_pct = {reserve_capital_pct}

    def populate_indicators(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe['atr'] = ta.atr(dataframe['high'], dataframe['low'], dataframe['close'], length=self.atr_period)
        dataframe['volatility'] = dataframe['atr'] / dataframe['close']
        return dataframe

    def populate_entry_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe.loc[
            dataframe['volatility'] > self.volatility_threshold,
            'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        dataframe.loc[
            dataframe['close'] > dataframe['close'].shift(1) * (1 + self.volatility * self.tp_multiplier),
            'exit_long'] = 1
        return dataframe
"""

TEMPLATE_MAP = {
    StrategyTemplate.TREND_FOLLOWING: TREND_FOLLOWING_TEMPLATE,
    StrategyTemplate.MEAN_REVERSION: MEAN_REVERSION_TEMPLATE,
    StrategyTemplate.BREAKOUT: BREAKOUT_TEMPLATE,
    StrategyTemplate.MOMENTUM: MOMENTUM_TEMPLATE,
    StrategyTemplate.VOLATILITY: VOLATILITY_TEMPLATE,
}

# DNA specifications for each template
TEMPLATE_SPECS: Dict[StrategyTemplate, List[DNASpec]] = {
    StrategyTemplate.TREND_FOLLOWING: [
        DNASpec(name="fast_period", type="int", min=5, max=50, default=8),
        DNASpec(name="slow_period", type="int", min=20, max=200, default=21),
        DNASpec(name="trend_threshold", type="float", min=0.001, max=0.05, default=0.01),
        DNASpec(name="rsi_period", type="int", min=5, max=30, default=14),
        DNASpec(name="rsi_overbought", type="int", min=60, max=90, default=70),
        DNASpec(name="rsi_oversold", type="int", min=10, max=40, default=30),
        DNASpec(name="position_size_pct", type="float", min=0.02, max=0.50, default=0.10),
        DNASpec(name="min_stake_usd", type="float", min=5.0, max=50.0, default=5.0),
        DNASpec(name="max_stake_usd", type="float", min=20.0, max=500.0, default=100.0),
        DNASpec(name="max_open_trades", type="int", min=1, max=5, default=1),
        DNASpec(name="risk_capital_pct", type="float", min=0.10, max=0.80, default=0.50),
        DNASpec(name="reserve_capital_pct", type="float", min=0.05, max=0.30, default=0.10),
    ],
    StrategyTemplate.MEAN_REVERSION: [
        DNASpec(name="bb_period", type="int", min=10, max=50, default=20),
        DNASpec(name="bb_std", type="float", min=1.0, max=3.0, default=2.0),
        DNASpec(name="rsi_period", type="int", min=5, max=30, default=14),
        DNASpec(name="rsi_overbought", type="int", min=60, max=90, default=70),
        DNASpec(name="rsi_oversold", type="int", min=10, max=40, default=30),
        DNASpec(name="mean_period", type="int", min=10, max=100, default=50),
        DNASpec(name="deviation_threshold", type="float", min=0.001, max=0.05, default=0.01),
        DNASpec(name="position_size_pct", type="float", min=0.02, max=0.50, default=0.10),
        DNASpec(name="min_stake_usd", type="float", min=5.0, max=50.0, default=5.0),
        DNASpec(name="max_stake_usd", type="float", min=20.0, max=500.0, default=100.0),
        DNASpec(name="max_open_trades", type="int", min=1, max=5, default=1),
        DNASpec(name="risk_capital_pct", type="float", min=0.10, max=0.80, default=0.50),
        DNASpec(name="reserve_capital_pct", type="float", min=0.05, max=0.30, default=0.10),
    ],
    StrategyTemplate.BREAKOUT: [
        DNASpec(name="lookback", type="int", min=10, max=100, default=20),
        DNASpec(name="atr_period", type="int", min=5, max=30, default=14),
        DNASpec(name="atr_multiplier", type="float", min=0.5, max=3.0, default=1.5),
        DNASpec(name="volume_factor", type="float", min=1.0, max=5.0, default=2.0),
        DNASpec(name="position_size_pct", type="float", min=0.02, max=0.50, default=0.10),
        DNASpec(name="min_stake_usd", type="float", min=5.0, max=50.0, default=5.0),
        DNASpec(name="max_stake_usd", type="float", min=20.0, max=500.0, default=100.0),
        DNASpec(name="max_open_trades", type="int", min=1, max=5, default=1),
        DNASpec(name="risk_capital_pct", type="float", min=0.10, max=0.80, default=0.50),
        DNASpec(name="reserve_capital_pct", type="float", min=0.05, max=0.30, default=0.10),
    ],
    StrategyTemplate.MOMENTUM: [
        DNASpec(name="momentum_period", type="int", min=5, max=50, default=10),
        DNASpec(name="signal_period", type="int", min=5, max=30, default=9),
        DNASpec(name="momentum_threshold", type="float", min=0.1, max=5.0, default=1.0),
        DNASpec(name="rsi_period", type="int", min=5, max=30, default=14),
        DNASpec(name="position_size_pct", type="float", min=0.02, max=0.50, default=0.10),
        DNASpec(name="min_stake_usd", type="float", min=5.0, max=50.0, default=5.0),
        DNASpec(name="max_stake_usd", type="float", min=20.0, max=500.0, default=100.0),
        DNASpec(name="max_open_trades", type="int", min=1, max=5, default=1),
        DNASpec(name="risk_capital_pct", type="float", min=0.10, max=0.80, default=0.50),
        DNASpec(name="reserve_capital_pct", type="float", min=0.05, max=0.30, default=0.10),
    ],
    StrategyTemplate.VOLATILITY: [
        DNASpec(name="atr_period", type="int", min=5, max=30, default=14),
        DNASpec(name="volatility_threshold", type="float", min=0.005, max=0.1, default=0.02),
        DNASpec(name="position_size_pct", type="float", min=0.02, max=0.50, default=0.10),
        DNASpec(name="min_stake_usd", type="float", min=5.0, max=50.0, default=5.0),
        DNASpec(name="max_stake_usd", type="float", min=20.0, max=500.0, default=100.0),
        DNASpec(name="max_open_trades", type="int", min=1, max=5, default=1),
        DNASpec(name="risk_capital_pct", type="float", min=0.10, max=0.80, default=0.50),
        DNASpec(name="reserve_capital_pct", type="float", min=0.05, max=0.30, default=0.10),
        DNASpec(name="tp_multiplier", type="float", min=1.0, max=5.0, default=2.0),
        DNASpec(name="sl_multiplier", type="float", min=0.5, max=3.0, default=1.5),
    ],
}
